/-
Copyright (c) 2026 Chokmah LLC. All rights reserved.
Private campaign artifact. Gates refute routes, not theorems.
-/

import FragileProofAudit.QTSPP.Stembridge

/-!
# Identity (3.2): the diagonal identity B(n,n) = 1 — parametric certificate

arXiv:0906.1018 §5.3 (Koutschan's algorithmic proof of Stembridge's TSPP
theorem). The paper certifies an order-7 recurrence operator `L` for the
diagonal `d_n = B'(n,n)` with:

  (i)   `(S_n − 1)` a right factor of `L` (so the constant sequence 1 also
        satisfies `L`; the paper checks this by reducing `L` modulo the
        ideal `(S_n − 1)`),
  (ii)  leading coefficient
        `256(2n+3)(2n+5)(2n+7)(2n+9)(2n+11)²(2n+13)²·p_1·p_2 ≠ 0` on `ℕ`
        (`p_1`, `p_2` irreducible of degrees 4, 12),
  (iii) the finite check `B'(1,1) = … = B'(7,7) = 1`.

RECOVERY STATUS (2026-09-24): the explicit order-7 coefficients arrived from
Christoph Koutschan (re-run at our request; `Bnn_op_0_a23r.txt`,
SHA-256 `d12c1027…b8570`) and are instantiated as the concrete
`koutschanCertificate` in `FragileProofAudit.QTSPP.KoutschanOperator`.
This module's parametric statement is retained as the general closing
argument. See `docs/blueprint/qtspp-q1.md` §8 for the recovery report.

This module therefore formalizes (3.2) PARAMETRICALLY: the certificate is
an explicit `DiagonalCertificate` structure (the order-7 coefficients `p`
plus the right-factor witness `q` with the Ore relations `L = Q·(S_n−1)`
unfolded — exactly the data a recovered certificate must supply). The
closing argument is fully proved, sorry-free:

  right-factor relations ⇒ coefficient sum telescopes to 0
    (`cert_annihilates_one`)
  ⇒ the constant-1 sequence satisfies `L`
  ⇒ `d = 1` by `recurrence_unique` (`QTSPP.Stembridge`).

Plugging in recovered coefficients reduces to discharging the structure
fields plus `hrec` (the `DFiniteSubstitute` output — needs the ∂-finite
description), `hlead` (via the factored leading coefficient), and `hinit`
(7 small determinants).
-/

namespace FragileProofAudit.QTSPP

/-- Certificate data for identity (3.2): the order-7 operator
    `L = Σ_{i=0}^7 p_i(n)·S_n^i` for the diagonal, together with its
    right-factor witness `Q = Σ_{j=0}^6 q_j(n)·S_n^j` such that
    `L = Q·(S_n − 1)`.

    In the univariate Ore algebra `ℚ(n)[S_n]` with `S_n·c(n) = c(n+1)·S_n`,
    `(Σ_j q_j S_n^j)·(S_n − 1) = Σ_j q_j S_n^{j+1} − Σ_j q_j S_n^j`,
    which unfolds to exactly the coefficient relations below. This is the
    machine-checkable form of the paper's "reducing this recurrence with
    the ideal generated by `S_n − 1` gives 0". -/
structure DiagonalCertificate where
  p : ℕ → ℕ → ℚ
  q : ℕ → ℕ → ℚ
  right_top : ∀ n, p 7 n = q 6 n
  right_mid : ∀ i ∈ Finset.Icc 1 6, ∀ n, p i n = q (i - 1) n - q i n
  right_bot : ∀ n, p 0 n = -(q 0 n)

/-- Partial telescoping sums: for `k ≤ 6` the first `k+1` coefficients sum
    to `−q_k`. -/
theorem DiagonalCertificate.partial_telescope (cert : DiagonalCertificate)
    (n k : ℕ) (hk : k ≤ 6) :
    ∑ i ∈ Finset.range (k + 1), cert.p i n = -(cert.q k n) := by
  induction k with
  | zero =>
    rw [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
      cert.right_bot n]
  | succ k ih =>
    have hkmem : k + 1 ∈ Finset.Icc 1 6 := Finset.mem_Icc.mpr ⟨by omega, by omega⟩
    rw [Finset.sum_range_succ, ih (by omega), cert.right_mid (k + 1) hkmem n,
      show k + 1 - 1 = k from by omega]
    ring

/-- The right-factor witness makes the full coefficient sum telescope to
    zero: the constant sequence `1` is annihilated by `L`. -/
theorem cert_annihilates_one (cert : DiagonalCertificate) (n : ℕ) :
    ∑ i ∈ Finset.range (7 + 1), cert.p i n * 1 = 0 := by
  simp only [mul_one]
  rw [Finset.sum_range_succ]
  have h6 : ∑ i ∈ Finset.range 7, cert.p i n = -(cert.q 6 n) :=
    cert.partial_telescope n 6 le_rfl
  rw [h6, cert.right_top n, neg_add_cancel]

/-- Identity (3.2), parametrically: given the order-7 certificate, a
    sequence `d` satisfying its recurrence with everywhere-nonzero leading
    coefficient and agreeing with `1` on the first 7 values is constantly
    `1`.

    Index note: the paper numbers `n ≥ 1` with `B'(1,1) = … = B'(7,7) = 1`;
    here `d i` corresponds to the paper's `B'(i+1, i+1)`, so `hinit` is the
    7-value finite check, and the recurrence — a statement about all
    `n ∈ ℕ` — transfers unchanged. -/
theorem diagonal_identity_of_certificate (cert : DiagonalCertificate)
    (d : ℕ → ℚ)
    (hlead : ∀ n, cert.p 7 n ≠ 0)
    (hrec : ∀ n, ∑ i ∈ Finset.range (7 + 1), cert.p i n * d (n + i) = 0)
    (hinit : ∀ i < 7, d i = 1) :
    d = fun _ => 1 := by
  apply recurrence_unique (m := 7) (p := cert.p) (f := d) (g := fun _ => 1)
  · exact hlead
  · exact hrec
  · intro n
    have h := cert_annihilates_one cert n
    simpa using h
  · intro i hi
    exact hinit i hi

end FragileProofAudit.QTSPP
