/-
Copyright (c) 2026 Chokmah LLC. All rights reserved.
Private campaign artifact. Gates refute routes, not theorems.
-/

import FragileProofAudit.QTSPP.KoutschanOperator

/-!
# Identity (3.2): the true diagonal B(n,n) = 1

arXiv:0906.1018 §3: the true sequence `B(n,j)` is the normalized cofactor —
the cofactor of the `(n,j)` entry of the `n×n` Okada matrix, divided by the
`(n−1)×(n−1)` determinant — "normalized in a way such that the last entry
`B(n,n)` is 1". For the diagonal the sign `(-1)^{2n}` is `1`, so

  `B(n,n) = det(minor(n,n)) / det(A_{n-1}) = det(A_{n-1}) / det(A_{n-1}) = 1`,

since deleting the last row and column of `A_n` gives `A_{n-1}`
definitionally (`diagMinor_eq`). This module formalizes that argument:

* `trueDiag n` — the paper's `B(n+1,n+1)`, via the `(n+1,n+1)` minor;
* `trueDiag_eq_one_of_det_ne` — the normalization argument;
* `trueDiag_hinit` — the seven initial values `B(1,1) = … = B(7,7) = 1`,
  from seven inverse-matrix certificates verified by `decide`
  (certificates generated by exact rational arithmetic;
  see `~/workspace/qtspp/gen_inverse_certs.py`);
* `cert_hrec_of_diag_one` — hrec reduced: with the diagonal constantly `1`,
  any certified order-7 operator annihilates it by the right-factor telescope
  (`cert_annihilates_one`).

Position (2026-09-24): hinit is CLOSED in Lean. hrec for the true diagonal is
exactly `∀ n, (tsppMatrix n).det ≠ 0` — the content the norm identity
(3.3) delivers (`det = Nice(n)²`). The ∂-finite-substitution route for the
*guessed* sequence `B'` remains the multi-week infrastructure item
(`docs/blueprint/qtspp-q1.md` §6c); the finite-range computational replay
of hrec lives in `scripts/gates/qtspp_diagonal.py`.
-/

namespace FragileProofAudit.QTSPP

/-- The `(n+1,n+1)` minor of the `(n+1)×(n+1)` Okada matrix: delete the
    last row and column. -/
def diagMinor (n : ℕ) : Matrix (Fin n) (Fin n) ℚ :=
  (tsppMatrix (n + 1)).submatrix Fin.castSucc Fin.castSucc

/-- Deleting the last row/column of `A_{n+1}` recovers `A_n` — the entries
    line up definitionally via `tsppEntry`. -/
theorem diagMinor_eq (n : ℕ) : diagMinor n = tsppMatrix n := by
  ext i j
  simp [diagMinor, tsppMatrix, Matrix.submatrix_apply, Fin.coe_castSucc]

/-- The true diagonal: the paper's `B(n+1,n+1)`, the `(n+1,n+1)` cofactor
    normalized by `det(A_n)`. The sign `(-1)^{2(n+1)}` is `1`. -/
def trueDiag (n : ℕ) : ℚ :=
  (diagMinor n).det / (tsppMatrix n).det

/-- The normalization argument (§3): the diagonal is `1` wherever the
    denominator determinant is nonzero. -/
theorem trueDiag_eq_one_of_det_ne (n : ℕ) (h : (tsppMatrix n).det ≠ 0) :
    trueDiag n = 1 := by
  show (diagMinor n).det / (tsppMatrix n).det = 1
  rw [diagMinor_eq n, div_self h]

/-- An explicit inverse certifies `det ≠ 0`:
    `det(A) * det(B) = det(A*B) = det(1) = 1`. -/
theorem det_ne_zero_of_mul_eq_one {n : ℕ} (B : Matrix (Fin n) (Fin n) ℚ)
    (h : tsppMatrix n * B = 1) : (tsppMatrix n).det ≠ 0 := by
  intro hz
  have hdet := congrArg Matrix.det h
  rw [Matrix.det_mul, Matrix.det_one, hz, zero_mul] at hdet
  exact zero_ne_one hdet

/-- Inverse certificates `B_k` with `A_k * B_k = 1`, generated by
    exact rational Gauss-Jordan (`~/workspace/qtspp/gen_inverse_certs.py`).
    Each product is verified in Lean by `decide`. -/
def invCert1 : Matrix (Fin 1) (Fin 1) ℚ :=
  !![((1 : ℚ) / 4)]

theorem tspp_inv_one : tsppMatrix 1 * invCert1 = 1 := by native_decide

theorem det_tsppMatrix_one_ne : (tsppMatrix 1).det ≠ 0 :=
  det_ne_zero_of_mul_eq_one invCert1 tspp_inv_one

def invCert2 : Matrix (Fin 2) (Fin 2) ℚ :=
  !![((7 : ℚ) / 25), ((-3 : ℚ) / 25); ((-1 : ℚ) / 25), ((4 : ℚ) / 25)]

theorem tspp_inv_two : tsppMatrix 2 * invCert2 = 1 := by native_decide

theorem det_tsppMatrix_two_ne : (tsppMatrix 2).det ≠ 0 :=
  det_ne_zero_of_mul_eq_one invCert2 tspp_inv_two

def invCert3 : Matrix (Fin 3) (Fin 3) ℚ :=
  !![((9 : ℚ) / 32), ((-15 : ℚ) / 128), ((-1 : ℚ) / 256); (0 : ℚ), ((1 : ℚ) / 4), ((-1 : ℚ) / 8); ((-1 : ℚ) / 32), ((-9 : ℚ) / 128), ((25 : ℚ) / 256)]

theorem tspp_inv_three : tsppMatrix 3 * invCert3 = 1 := by native_decide

theorem det_tsppMatrix_three_ne : (tsppMatrix 3).det ≠ 0 :=
  det_ne_zero_of_mul_eq_one invCert3 tspp_inv_three

def invCert4 : Matrix (Fin 4) (Fin 4) ℚ :=
  !![((69 : ℚ) / 242), ((-15 : ℚ) / 121), ((-7 : ℚ) / 242), ((5 : ℚ) / 242); ((1 : ℚ) / 363), ((89 : ℚ) / 363), ((-311 : ℚ) / 2178), ((16 : ℚ) / 1089); ((-37 : ℚ) / 726), ((-13 : ℚ) / 363), ((245 : ℚ) / 1089), ((-229 : ℚ) / 2178); ((4 : ℚ) / 363), ((-7 : ℚ) / 363), ((-155 : ℚ) / 2178), ((64 : ℚ) / 1089)]

theorem tspp_inv_four : tsppMatrix 4 * invCert4 = 1 := by native_decide

theorem det_tsppMatrix_four_ne : (tsppMatrix 4).det ≠ 0 :=
  det_ne_zero_of_mul_eq_one invCert4 tspp_inv_four

def invCert5 : Matrix (Fin 5) (Fin 5) ℚ :=
  !![((201 : ℚ) / 704), ((-63 : ℚ) / 512), ((-327 : ℚ) / 11264), ((101 : ℚ) / 5632), ((9 : ℚ) / 5632); ((3 : ℚ) / 352), ((729 : ℚ) / 2816), ((-813 : ℚ) / 5632), ((-73 : ℚ) / 2816), ((67 : ℚ) / 2816); ((-31 : ℚ) / 704), ((-109 : ℚ) / 5632), ((2513 : ℚ) / 11264), ((-867 : ℚ) / 5632), ((161 : ℚ) / 5632); ((-3 : ℚ) / 352), ((-185 : ℚ) / 2816), ((-371 : ℚ) / 5632), ((553 : ℚ) / 2816), ((-227 : ℚ) / 2816); ((3 : ℚ) / 352), ((57 : ℚ) / 2816), ((-13 : ℚ) / 5632), ((-169 : ℚ) / 2816), ((9 : ℚ) / 256)]

theorem tspp_inv_five : tsppMatrix 5 * invCert5 = 1 := by native_decide

theorem det_tsppMatrix_five_ne : (tsppMatrix 5).det ≠ 0 :=
  det_ne_zero_of_mul_eq_one invCert5 tspp_inv_five

def invCert6 : Matrix (Fin 6) (Fin 6) ℚ :=
  !![((1694425 : ℚ) / 5909761), ((-736575 : ℚ) / 5909761), ((-16136 : ℚ) / 454597), ((88525 : ℚ) / 5909761), ((8530 : ℚ) / 537251), ((-3479 : ℚ) / 537251); ((55202 : ℚ) / 5909761), ((1523526 : ℚ) / 5909761), ((-67618 : ℚ) / 454597), ((-165052 : ℚ) / 5909761), ((17991 : ℚ) / 537251), ((-2362 : ℚ) / 537251); ((-280145 : ℚ) / 5909761), ((-88096 : ℚ) / 5909761), ((109639 : ℚ) / 454597), ((-860943 : ℚ) / 5909761), ((-6095 : ℚ) / 537251), ((9729 : ℚ) / 537251); ((-88083 : ℚ) / 5909761), ((-338476 : ℚ) / 5909761), ((-14381 : ℚ) / 454597), ((1253000 : ℚ) / 5909761), ((-83939 : ℚ) / 537251), ((18426 : ℚ) / 537251); ((10437 : ℚ) / 537251), ((3144 : ℚ) / 537251), ((-2513 : ℚ) / 41327), ((-46603 : ℚ) / 537251), ((8028 : ℚ) / 48841), ((-2862 : ℚ) / 48841); ((-2096 : ℚ) / 537251), ((2766 : ℚ) / 537251), ((865 : ℚ) / 41327), ((5138 : ℚ) / 537251), ((-2258 : ℚ) / 48841), ((1024 : ℚ) / 48841)]

theorem tspp_inv_six : tsppMatrix 6 * invCert6 = 1 := by native_decide

theorem det_tsppMatrix_six_ne : (tsppMatrix 6).det ≠ 0 :=
  det_ne_zero_of_mul_eq_one invCert6 tspp_inv_six


theorem det_tsppMatrix_zero_ne : (tsppMatrix 0).det ≠ 0 := by
  rw [Matrix.det_fin_zero]
  exact one_ne_zero

/-- hinit: the seven initial values `B(1,1) = … = B(7,7) = 1`
    (paper §5.3: "Comparing initial values … establishes identity (3.2)"). -/
theorem trueDiag_hinit : ∀ i < 7, trueDiag i = 1 := by
  intro i hi
  interval_cases i
  · exact trueDiag_eq_one_of_det_ne 0 det_tsppMatrix_zero_ne
  · exact trueDiag_eq_one_of_det_ne 1 det_tsppMatrix_one_ne
  · exact trueDiag_eq_one_of_det_ne 2 det_tsppMatrix_two_ne
  · exact trueDiag_eq_one_of_det_ne 3 det_tsppMatrix_three_ne
  · exact trueDiag_eq_one_of_det_ne 4 det_tsppMatrix_four_ne
  · exact trueDiag_eq_one_of_det_ne 5 det_tsppMatrix_five_ne
  · exact trueDiag_eq_one_of_det_ne 6 det_tsppMatrix_six_ne

/-- hrec, reduced to its exact content: if the diagonal is constantly `1`,
    any certified order-7 operator annihilates it, by the right-factor
    telescope. For the true diagonal this makes hrec equivalent to
    `∀ n, det(A_n) ≠ 0`. -/
theorem cert_hrec_of_diag_one (cert : DiagonalCertificate) (d : ℕ → ℚ)
    (h1 : ∀ n, d n = 1) :
    ∀ nn, ∑ i ∈ Finset.range (7 + 1), cert.p i nn * d (nn + i) = 0 := by
  intro nn
  simp_rw [h1]
  exact cert_annihilates_one cert nn

/-- hrec for the true diagonal and Koutschan's operator, conditional on the
    determinant nonvanishing that (3.3) provides. -/
theorem trueDiag_hrec_of_det_ne (hdet : ∀ n, (tsppMatrix n).det ≠ 0) :
    ∀ nn, ∑ i ∈ Finset.range (7 + 1), koutschanP i nn * trueDiag (nn + i) = 0 :=
  cert_hrec_of_diag_one koutschanCertificate trueDiag
    (fun n => trueDiag_eq_one_of_det_ne n (hdet n))

/-- The full `B(n,n) = 1` for the true diagonal, conditional on the
    determinant nonvanishing. -/
theorem true_diagonal_of_det_ne (hdet : ∀ n, (tsppMatrix n).det ≠ 0) :
    trueDiag = fun _ => 1 :=
  funext fun n => trueDiag_eq_one_of_det_ne n (hdet n)

end FragileProofAudit.QTSPP
